name: $(Rev:r)
jobs:
- job: IonideFsharp-Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core Sdk from global.json'
    inputs:
      useGlobalJson: true
  - task: NodeTool@0
    displayName: Install Node
    inputs:
      versionSpec: "10.15.1"
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: Install Yarn
    inputs:
      versionSpec: "1.10.1"
  - script: .\build.cmd InstallVSCE
    displayName: Install VSCE
  - script: .\build.cmd BuildPackag
    displayName: BuildPackage
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: 'temp'
      artifactName: 'ionide-fsharp-vscode-ext'
- job: IonideFsharp-MacOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core Sdk from global.json'
    inputs:
      useGlobalJson: true
  - task: NodeTool@0
    displayName: Install Node
    inputs:
      versionSpec: "10.15.1"
  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
    displayName: Install Yarn
    inputs:
      versionSpec: "1.10.1"
  - script: .\build.sh InstallVSCE
    displayName: Install VSCE
  - script: .\build.sh BuildPackage extVersionSuffix=%ExtVersionSuffix%
    displayName: BuildPackage

